# 目录
## 1. 导入模块
## 2. 常量`tf.constant`
  - ### 2.1 索引操作
  - ### 2.2 算子操作
    - `tf.square`
	- `tf.transpose`
	
  - ### 2.3 `numpy`转换
  - ### 2.4 `Scalars`
  
## 3. `tf.strings`
  - `tf.strings.length`
  - `tf.strings.unicode_decode`

## 4. `tf.RaggedTensor`
  - `tf.ragged.constant`
  - ### 4.1 索引操作
  - ### 4.2 `tf.concat` 合并操作
  - ### 4.3 `RaggedTensor` 转换 `Tensor`
    - `to_tensor`
	
## 5. `tf.SparseTensor`稀疏Tensor
  - ### 5.1 `SparseTensor` 转化为 `Tensor`
    - `tf.sparse.to_dense`
	
  - ### 5.2 `SparseTensor`的算子操作
    - `tf.sparse.sparse_dense_matmul`
	
  - ### 5.3 indices 不按照顺序的 `SparseTensor`
    - `tf.sparse.reorder`

## 6. `tf.Variable` 变量
  - ### 6.1 `Variable` 转化为 `Tensor` 和 `numpy`
  - ### 6.2 变量的赋予、加法、减法操作
    - `assign`
	- `assign_add`
	- `assign_sub`

## 1. 导入模块

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn

from tensorflow import keras
import tensorflow as tf
import sys
import os
import time
import datetime

for module in [np, pd, mpl, sklearn, keras, tf]:
    print(module.__name__, module.__version__)

numpy 1.18.1
pandas 0.25.3
matplotlib 3.1.2
sklearn 0.22.1
tensorflow_core.python.keras.api._v2.keras 2.2.4-tf
tensorflow 2.1.0


## 2. 常量`tf.constant`

In [2]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])

  - ### 2.1 索引操作

In [9]:
print(a)
print(a[1]) # 取一行
print(a[:, 1:]) # 切一部分
print(a[..., 1]) # 取一列

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


  - ### 2.2 算子操作

In [4]:
print(a+11) # 加法操作
print(tf.square(a)) # 平方操作
print(a @ tf.transpose(a)) # 矩阵乘法操作

tf.Tensor(
[[12 13 14]
 [15 16 17]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


  - ### 2.3 `numpy`转换

In [5]:
print(a.numpy()) # Tensor 转 numpy
print(np.square(a)) # Tensor 使用 numpy的操作

np_t = np.array([[1, 2, 3], [4, 5, 6]])
print(tf.constant(np_t)) # numpy 转 Tensor

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


  - ### 2.4 Scalars

In [6]:
t = tf.constant(1.3545)
print(t)

print(t.numpy())

print(t.shape)

tf.Tensor(1.3545, shape=(), dtype=float32)
1.3545
()


## 3. `tf.strings`

In [7]:
t = tf.constant("caffe")
print(t)

print(tf.strings.length(t))
print(tf.strings.length(t, unit="UTF8_CHAR"))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor(b'caffe', shape=(), dtype=string)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 102 101], shape=(5,), dtype=int32)


In [8]:
t = tf.constant(["caffe", "coffe", "咖啡"])
print(t)

print(tf.strings.length(t, unit="UTF8_CHAR"))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor([b'caffe' b'coffe' b'\xe5\x92\x96\xe5\x95\xa1'], shape=(3,), dtype=string)
tf.Tensor([5 5 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 102, 101], [99, 111, 102, 102, 101], [21654, 21857]]>


>`tf.RaggedTensor` 包装参差不齐的矩阵

## 4. `tf.RaggedTensor`

In [11]:
r = tf.ragged.constant([[1,2,3,4], [1, 2], [], [1,2,3]])

  - ### 4.1 索引操作

In [12]:
print(r[1]) # 取一行
print(r[1:2])  # 取一部分

tf.Tensor([1 2], shape=(2,), dtype=int32)
<tf.RaggedTensor [[1, 2]]>


  - ### 4.2 `tf.concat` 合并操作

In [18]:
r2 = tf.ragged.constant([[34, 56, 89], [1]])
print(tf.concat([r, r2], axis=0)) # 按照行合并

<tf.RaggedTensor [[1, 2, 3, 4], [1, 2], [], [1, 2, 3], [34, 56, 89], [1]]>


In [19]:
r3 = tf.ragged.constant([[34, 56, 89], [1], [7, 9, 5], []])
print(tf.concat([r, r3], axis=1)) # 按照列合并，行必须都一样，否则报错

<tf.RaggedTensor [[1, 2, 3, 4, 34, 56, 89], [1, 2, 1], [7, 9, 5], [1, 2, 3]]>


  - ### 4.3 `RaggedTensor` 转换 `Tensor`

In [20]:
print(r.to_tensor())

tf.Tensor(
[[1 2 3 4]
 [1 2 0 0]
 [0 0 0 0]
 [1 2 3 0]], shape=(4, 4), dtype=int32)


## 5. `tf.SparseTensor`稀疏Tensor

In [21]:
s = tf.SparseTensor(
    indices=[[0, 1], [1, 0], [2, 3]],
    values=[1., 3., 4.],
    dense_shape=[3, 4]
)
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


  - ### 5.1 `SparseTensor` 转化为 `Tensor`

In [22]:
print(tf.sparse.to_dense(s))

tf.Tensor(
[[0. 1. 0. 0.]
 [3. 0. 0. 0.]
 [0. 0. 0. 4.]], shape=(3, 4), dtype=float32)


  - ### 5.2 `SparseTensor`的算子操作

In [25]:
s2 = s * 2  # 乘法操作

try:
    s3 = s + 3 # 加法操作报错
except TypeError as e:
    print(e)
    
s4 = tf.constant([[1., 2.], [1., 2.], [1., 2.], [1., 2.]])
print(tf.sparse.sparse_dense_matmul(s, s4))  # 矩阵操作

unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[1. 2.]
 [3. 6.]
 [4. 8.]], shape=(3, 2), dtype=float32)


  - ### 5.3 indices 不按照顺序的 `SparseTensor`

In [27]:
s5 = tf.SparseTensor(
    indices=[[1, 1], [0, 1], [2, 3]],
    values=[1., 3., 4.],
    dense_shape=[3, 4]
)
print(s5)

try:
    print(tf.sparse.to_dense(s5))  # 不按顺序的报错
except Exception as e:
    print(e)
    
s6 = tf.sparse.reorder(s5)
print(tf.sparse.to_dense(s6))


SparseTensor(indices=tf.Tensor(
[[1 1]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
indices[1] = [0,1] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.

 [Op:SparseToDense]
tf.Tensor(
[[0. 3. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 4.]], shape=(3, 4), dtype=float32)


## 6. `tf.Variable` 变量

In [29]:
v = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


  - ### 6.1 `Variable` 转化为 `Tensor` 和 `numpy`

In [30]:
print(v.value()) # 转为 Tensor

print(v.numpy()) # 转为 numpy

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


  - ### 6.2 变量的赋予、加法、减法操作

In [36]:
v.assign(2*v)

print(v.numpy())

v[0, 1].assign(55)
print(v.numpy())

v[1].assign([8.0, 9.0, 6.0])
print(v.numpy())

v2 = tf.Variable([[10.0, 20.0, 30.0], [40.0, 50.0, 60.0]])
v.assign_add(v2)
print(v.numpy())

v.assign_sub(v2)
print(v.numpy())

[[ 52. 150. 156.]
 [ 96. 118. 132.]]
[[ 52.  55. 156.]
 [ 96. 118. 132.]]
[[ 52.  55. 156.]
 [  8.   9.   6.]]
[[ 62.  75. 186.]
 [ 48.  59.  66.]]
[[ 52.  55. 156.]
 [  8.   9.   6.]]
