In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn

from tensorflow import keras
import tensorflow as tf
import sys
import os
import time
import datetime

for module in [np, pd, mpl, sklearn, keras, tf]:
    print(module.__name__, module.__version__)
    
gpus = tf.config.experimental.list_physical_devices("GPU")
tf.config.experimental.set_memory_growth(gpus[0], True)

numpy 1.18.1
pandas 0.25.3
matplotlib 3.1.2
sklearn 0.22.1
tensorflow_core.python.keras.api._v2.keras 2.2.4-tf
tensorflow 2.1.0


In [2]:
keras_model = keras.models.load_model("./keras_hdf5_model/save/fashion_mnist.h5")

In [5]:
keras_model(np.ones((1, 28, 28, 1)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.07633319, 0.10343505, 0.09567624, 0.02766261, 0.05517917,
        0.01143559, 0.10081402, 0.01948361, 0.4656996 , 0.0442809 ]],
      dtype=float32)>

In [7]:
run_model = tf.function(lambda x: keras_model(x))
keras_concrete_func = run_model.get_concrete_function(
    tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype)
)

In [9]:
keras_concrete_func(tf.constant(np.ones((1, 28, 28, 1)), dtype=tf.float32))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.07633319, 0.10343505, 0.09567624, 0.02766261, 0.05517917,
        0.01143559, 0.10081402, 0.01948361, 0.4656996 , 0.0442809 ]],
      dtype=float32)>